spring.datasource.url=${DB_URL:jdbc:h2:mem:autoflexdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}