-- =======================================================
-- Migration V1: Criação das tabelas principais do sistema
-- =======================================================

CREATE TABLE raw_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_raw_material_stock_non_negative CHECK (stock_quantity >= 0)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    "value" DECIMAL(10, 2) NOT NULL,
    CONSTRAINT chk_product_value_positive CHECK ("value" > 0)
);

CREATE TABLE product_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    raw_material_id BIGINT NOT NULL,
    quantity_required INTEGER NOT NULL,
    CONSTRAINT fk_components_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_components_raw_material FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE RESTRICT,
    CONSTRAINT chk_component_quantity_positive CHECK (quantity_required > 0)
);

CREATE INDEX idx_product_components_product_id ON product_components(product_id);
CREATE INDEX idx_product_components_raw_material_id ON product_components(raw_material_id);
