-- =======================================================
-- Migration V3: Criação das tabelas de Ordens de Produção
-- =======================================================

CREATE TABLE production_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_value DECIMAL(10, 2) NOT NULL,
    total_items INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'COMPLETED'
);

CREATE TABLE production_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    unit_value DECIMAL(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);

CREATE INDEX idx_production_order_items_order_id ON production_order_items(order_id);
CREATE INDEX idx_production_orders_created_at ON production_orders(created_at);
